function [] = export_text(knowledge_instance, textfile, targetname, solution, handles)

% EXPORT_TEXT - Export a given input solution as a text file.
%
% Usage: [] = export_text(knowledge_instance, textfile, targetname,
% solution, handles)
%

% Get items and microtonic transposition from cureent solution
n_inst = length(solution)/2;
items_idx = ((1:1:n_inst)*2)-1;
transpo_idx = items_idx+1;
items = solution(items_idx);
transpo = solution(transpo_idx);

% open text file
fid = fopen(textfile, 'w');

% Print header
fprintf(fid, 'Target: %s\n\n', targetname);

% Iterate on current solution's items
for k = 1:n_inst
    
    % Print item's position in orchestra
    fprintf(fid, '%-4d', k);
    
    % Print item info
    if items{k}
        fprintf(fid, '%-30s', knowledge_instance.database_contents.uri{items{k}});
        fprintf(fid, '%s\n',transpo{k});
    else
        fprintf(fid, '-\n');
    end
    
end

% Print footer
fprintf(fid, '\n///\nGenerated by Orchidee - %s', datestr(now));

% Close file
fclose(fid);
    
    