function nomenclature = nomenclature(knowledge_instance)

% NOMENCLATURE - Theoretic table of instrument families, folders, and
% symbols. It may contains instruments that are NOT in the current
% database, in order to help the user when adding new instrument (hopefully
% avoiding errors when naming file and folders). It is also used for
% automatically sort the instrument list in the traditional orchestral
% order.
% 
% Usage: nomenclature = nomenclature(knowledge_instance)
%

nomenclature = { ...
    'Flutes'            'Piccolo'                   'Picc'      ;... 
    'Flutes'            'Flute'                     'Fl'        ;...
    'Flutes'            'Alto-Flute'                'AlFl'       ;...
    'Flutes'            'Bass-Flute'                'BFl'       ;...
    'Flutes'            'Contrabass-Flute'          'CbFl'      ;...
...
    'Oboes'             'Oboe'                      'Ob'        ;...
    'Oboes'             'Oboe-dAmore'               'ObAm'      ;...
    'Oboes'             'English-Horn'              'EH'        ;...
    'Oboes'             'Heckelphone'               'Heck'      ;...
...
    'Clarinets'         'Piccolo-Clarinet-Ab'       'PiClAb'    ;...
    'Clarinets'         'Clarinet-Eb'               'ClEb'      ;...
    'Clarinets'         'Piccolo-Clarinet-D'        'PiClD'     ;...
    'Clarinets'         'Clarinet-C'                'ClC'       ;...
    'Clarinets'         'Clarinet-Bb'               'ClBb'      ;...
    'Clarinets'         'Clarinet-A'                'ClA'       ;...
    'Clarinets'         'Basset-Horn-F'             'BstHn'     ;...
    'Clarinets'         'Alto-Clarinet-Eb'          'AlClEb'    ;...
    'Clarinets'         'Bass-Clarinet-Bb'          'BClBb'     ;...
    'Clarinets'         'Bass-Clarinet-A'           'BsClA'     ;...
    'Clarinets'         'Contra-Alto-Clarinet-Eb'   'CtAlClEb'  ;...
    'Clarinets'         'Contrabass-Clarinet-Bb'    'CbClBb'    ;...
...
    'Bassoons'          'Bassoon'                   'Bn'        ;...
    'Bassoons'          'Contrabassoon'             'Cbn'       ;...
...
    'Saxophones'        'Soprano-Sax'               'SoSax'     ;...
    'Saxophones'        'Alto-Sax'                  'ASax'      ;...
    'Saxophones'        'Tenor-Sax'                 'TnSax'     ;...
    'Saxophones'        'Baritone-Sax'              'BarSax'    ;...
    'Saxophones'        'Bass-Sax'                  'BsSax'     ;...
    'Saxophones'        'Contrabass-Sax'            'CbSax'     ;...
...
    'Horns'             'Horn'                      'Hn'        ;...
...
    'Trumpets'          'Piccolo-Trumpet-Bb'        'PiTpBb'    ;...
    'Trumpets'          'Piccolo-Trumpet-A'         'PiTpA'     ;...
    'Trumpets'          'High-Trumpet-F'            'HgTpF'     ;...
    'Trumpets'          'High-Trumpet-Eb'           'HgTpEb'    ;...
    'Trumpets'          'High-Trumpet-D'            'HgTpD'     ;...
    'Trumpets'          'Cornet-Eb'                 'CntEb'     ;...
    'Trumpets'          'Trumpet-C'                 'TpC'       ;...
    'Trumpets'          'Trumpet-Bb'                'TpBb'      ;...
    'Trumpets'          'Cornet-Bb'                 'CntBb'     ;...
    'Trumpets'          'Alto-Trumpet-F'            'AlTpF'     ;...
    'Trumpets'          'Bass-Trumpet-Eb'           'BsTpEb'    ;...
    'Trumpets'          'Bass-Trumpet-C'            'BsTpC'     ;...
    'Trumpets'          'Bass-Trumpet-Bb'           'BsTpBb'    ;...
...
    'Trombones'         'Alto-Trombone'             'AlTbn'     ;...
    'Trombones'         'Tenor-Trombone'            'TTbn'      ;...
    'Trombones'         'Bass-Trombone'             'BTbn'      ;...
    'Trombones'         'Contrabass-Trombone'       'CbTbn'     ;...
...
    'Tubas'             'Euphonium'                 'Eup'       ;...
    'Tubas'             'Bass-Tuba'                 'BTb'       ;...
    'Tubas'             'Contrabass-Tuba'           'CbTb'      ;...
...
    'Saxhorns'          'Flugelhorn'                'Flg'       ;...
...
    'Keyboards'         'Piano'                     'Pn'        ;...
    'Keyboards'         'Celesta'                   'Cel'       ;...
    'Keyboards'         'Harpsichord'               'Hpscd'     ;...
...
    'Plucked-Strings'   'Harp'                      'Hp'        ;...
    'Plucked-Strings'   'Guitar'                    'Gtr'       ;...
    'Plucked-Strings'   'Mandolin'                  'Mdl'       ;...
...
    'Strings'           'Violin'                    'Vn'        ;...
    'Strings'           'Viola'                     'Va'        ;...
    'Strings'           'Violoncello'               'Vc'        ;...
    'Strings'           'Contrabass'                'Cb'        ;...
    'Strings'           'ViolinEnsemble'            'Vns'        ;...
    'Strings'           'ViolaEnsemble'             'Vas'        ;...
    'Strings'           'VioloncelloEnsemble'       'Vcs'        ;...
    'Strings'           'ContrabassEnsemble'        'Cbs'        ;...
    };